### ISSUE TITLE
Gauge pin 140% [BUG]

### ISSUE THREAD

**Issue by AshExistsSometimes** [solent-group/StudioModule2024#56]
**Describe the bug**
Gauge pin has to be at around 140% before the exit door opens

**To Reproduce**
Steps to reproduce the behaviour:
1. shoot boiler
2. continue shooting boiler until it displays as full, the door wont open
3. refill gun and shoot it some more
4. gauge should be displaying around 140% before the door actually opens

**Expected behavior**
door should open by time pin touches little bronze peg at right side of the gauge

**Screenshots**
![Gauge moment](https://github.com/solent-group/StudioModule2024/assets/156530724/42967cf3-6061-4d9a-b83f-29823ea87925)

**Game build num**
0.0.3

**Comment by Jakilutra** [comment]
So do the pegs constrain the movement of the pin to less than 180 degrees? If so, is this angle known?

**Comment by Jakilutra** [comment]
I’ve figured it out. About 2.5 degrees both sides, so {0, 35, 70, 105, 140, 175} works.

**Comment by Jakilutra** [comment]
Fixed this pending a merge (but it'll be changing again)
